// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtbcLTTgBMq3pYRr_c1fDkHw9tyydKHDo',
    appId: '1:17056414326:web:692687277bf73f9b007d57',
    messagingSenderId: '17056414326',
    projectId: 'absensiosjur',
    authDomain: 'absensiosjur.firebaseapp.com',
    storageBucket: 'absensiosjur.appspot.com',
    measurementId: 'G-8HCSB559Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuE2A_UWvZfpSxe1H_8nOPws7VoyRV32c',
    appId: '1:17056414326:android:832e5cfb7bee5696007d57',
    messagingSenderId: '17056414326',
    projectId: 'absensiosjur',
    storageBucket: 'absensiosjur.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQPJ6PNfBDIfpFPeFxxygtB2_eg00pUXg',
    appId: '1:17056414326:ios:bf23cb573bce9757007d57',
    messagingSenderId: '17056414326',
    projectId: 'absensiosjur',
    storageBucket: 'absensiosjur.appspot.com',
    iosClientId: '17056414326-t1jr2jl3a1cad0033g7brsv68us5rl1j.apps.googleusercontent.com',
    iosBundleId: 'com.absensi.absensiOsjur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQPJ6PNfBDIfpFPeFxxygtB2_eg00pUXg',
    appId: '1:17056414326:ios:bf23cb573bce9757007d57',
    messagingSenderId: '17056414326',
    projectId: 'absensiosjur',
    storageBucket: 'absensiosjur.appspot.com',
    iosClientId: '17056414326-t1jr2jl3a1cad0033g7brsv68us5rl1j.apps.googleusercontent.com',
    iosBundleId: 'com.absensi.absensiOsjur',
  );
}
